name: NuGet Push Azure

on: [workflow_dispatch]

env:
  AZURE_ARTIFACTS_FEED_URL: ${{ secrets.AZURE_ARTIFACTS_FEED_URL }}

jobs:
  build-test-prep-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          DOTNET_INSTALL_DIR: /usr/share/dotnet
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_PAT }}
          
      - name: Create the package
        run: dotnet test -c Release && dotnet pack -c Release --output nupkgs
        
      - name: Publish the package to NuGet.org
        env:
          NUGET_KEY: ${{secrets.NUGET_KEY}}
        run: dotnet nuget push nupkgs/*.nupkg --api-key AzureArtifacts --skip-duplicate
